os: linux
dist: bionic
language: python
python:
- 3.9
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_56635d5d55b3_key -iv $encrypted_56635d5d55b3_iv
  -in do_ssh_key.enc -out ssh_keys/do_ssh_key -d
- openssl aes-256-cbc -K $encrypted_<REPLACE_ME>_key -iv $encrypted_<REPLACE_ME>_iv
  -in do_ssh_key.enc -out /tmp/git_deploy_key -d
- chmod 600 /tmp/git_deploy_key
- echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
- eval "$(ssh-agent -s)"
- DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
install:
- docker --version
stages:
- docker_build
- deploy
jobs:
  include:
  - stage: docker_build
    name: build and push docker
    script:
    - echo "LOGIN"
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - echo "BUILD"
    - docker build -t $DOCKER_USERNAME/web_image:latest . -f ./minitwit_frontend/Dockerfile
    - docker build -t $DOCKER_USERNAME/proxy_image:latest . -f ./minitwit_frontend/Dockerfileproxy
    - docker build -t $DOCKER_USERNAME/db_image:latest . -f Dockerfile-db
    - echo "PUSH"
    - docker push $DOCKER_USERNAME/web_image:latest
    - docker push $DOCKER_USERNAME/proxy_image:latest
    - docker push $DOCKER_USERNAME/db_image:latest
  - stage: deploy
    name: deploy new version
    install: skip
    script: |
      ssh -o "StrictHostKeyChecking no" ${MT_USER}@${MT_SERVER} \
      "source /root/.bash_profile && \
      cd /vagrant && \
      docker-compose pull && \
      docker-compose up -d && \
