version: '3.5'

networks:
  main:
    name: minitwit-network

services:
  db:
    image: postgres
    container_name: minitwit_db
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    networks:
      - main
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    image: ${DOCKER_USERNAME}/minitwit_web
    container_name: minitwit_web
    env_file:
      - .env
    depends_on:
     - db
    networks:
      - main
    ports:
      - '8000:8000'
    volumes:
      - static_data:/vol/web
    restart: always

  api:
<<<<<<< HEAD
<<<<<<< HEAD
    image: ${DOCKER_USERNAME}/minitwit_api
    container_name: minitwit_api
=======
    build:
      context: ./minitwit_backend
    command: python manage.py runserver 0.0.0.0:8080
    container_name: api
    volumes:
      - .:/code
    ports:
      - "8080:8080"
>>>>>>> bf30413b734096cc131a9d78dec943f9c4150f40
    depends_on:
     - db
    networks:
<<<<<<< HEAD
      - main
=======
      - minitwit 
    environment: 
      - DEBUG=1
    depends_on: 
      - grafana
      - prometheus

  web:
    build:
      context: ./minitwit_frontend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
>>>>>>> bf30413b734096cc131a9d78dec943f9c4150f40
=======
    image: ${DOCKER_USERNAME}/minitwit_api
    container_name: minitwit_api
    env_file:
      - .env
    depends_on:
     - db
    networks:
      - main
>>>>>>> dd9cd763dfbcbb1360858c68cbe36b4d3cacf5fe
    ports:
      - '9000:9000'
    volumes:
      - static_data:/vol/api
    restart: always

  proxy:
    image: ${DOCKER_USERNAME}/minitwit_proxy
    container_name: minitwit_proxy
    depends_on:
      - web
      - api
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> dd9cd763dfbcbb1360858c68cbe36b4d3cacf5fe
      - main
    ports:
      - '80:8080'
    volumes:
      - static_data:/vol/static
<<<<<<< HEAD
    restart: always
=======
      - minitwit 
    environment: 
      - DEBUG=1
    depends_on: 
      - grafana
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    # volumes:
    #   - grafana_data:/var/lib/grafana
    #   - ./grafana/provisioning/:/etc/grafana/provisioning/
=======
    env_file:
      - .env
>>>>>>> dd9cd763dfbcbb1360858c68cbe36b4d3cacf5fe
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - proxy 
    ports:
<<<<<<< HEAD
      - 9090:9090
>>>>>>> bf30413b734096cc131a9d78dec943f9c4150f40
=======
      - "9090:9090"
    networks:
      - main 

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus 
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - main 
>>>>>>> dd9cd763dfbcbb1360858c68cbe36b4d3cacf5fe


volumes:
  postgres:
  static_data:
  grafana_data:
  prometheus_data:
