version: "3.5"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - minitwit 

  api:
    build:
      context: ./minitwit_backend
    command: python manage.py runserver 0.0.0.0:8080
    container_name: api
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - minitwit 
    environment: 
      - DEBUG=1
    depends_on: 
      - grafana
      - prometheus

  web:
    build:
      context: ./minitwit_frontend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - minitwit 
    environment: 
      - DEBUG=1
    depends_on: 
      - grafana
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    # volumes:
    #   - grafana_data:/var/lib/grafana
    #   - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

networks:
  minitwit:
    driver: bridge

volumes:
  postgres:
