version: "3.9"

services:
  db:
    container_name: minitwit_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - minitwit 

  api:
    container_name: minitwit_api
    build:
      context: ./minitwit_backend

    command: ["./wait-for-it.sh", "db", "--", "python3 manage.py runserver 0.0.0.0:8080"]
    volumes:
      - .:/minitwit_api
    ports:
      - "8000:8000"
    networks:
      - minitwit 
    depends_on:
      - db

networks:
  minitwit:
    driver: bridge

volumes:
  postgres:
