FROM nginxinc/nginx-unprivileged:1-alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/uwsgi_params /etc/nginx/uwsgi_params

USER root

RUN mkdir -p /vol/static
RUN chmod 755 /vol/static

#USER nginx
