version: "3.5"


networks:
  main:
    name: minitwit-network

services:
  db:
    image: postgres
    container_name: minitwit_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    env_file: 
      - .postgres.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main
    restart: always

  api:
    build:
      context: ./minitwit_backend
    container_name: minitwit_api

    # command: python manage.py runserver 127.0.0.1:8080
    # volumes:
    #   - .:/code
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - main
    env_file:
      - .api.env
    restart: always

  web:
    build:
      context: ./minitwit_frontend
    container_name: minitwit_web
    # volumes:
    #   - .:/code
    ports:
      - "8000:8000"
    volumes:
      - static_data:/vol/static
    depends_on:
      - db
    networks:
      - main
    env_file:
      - .web.env
    # environment: 
    #   - SECRET_KEY=thisshouldbesecret
    #   - DB_NAME=minitwit
    #   - DB_USER=postgres
    #   - DB_PASSWORD=changeme
    #   - DB_HOST=db
    #   - ALLOWED_HOSTS=127.0.0.1,localhost,minitwititu.dk
    restart: always
  
  proxy:
    build:
      context: ./nginx
    container_name: minitwit_web

    volumes:
      - static_data:/vol/static
    networks:
      - main
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    restart: always


# networks:
#   minitwit:
#     driver: bridge

volumes:
  postgres:
  static_data:
