version: '3.5'

networks:
  main:
    name: minitwit-network

services:
  db:
    # image: ${DOCKER_USERNAME}/minitwit_db
    image: postgres
    container_name: minitwit_db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: changeme 
      POSTGRES_DATABASE: minitwit 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    networks:
      - main
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] 
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    image: ${DOCKER_USERNAME}/minitwit_web
    container_name: minitwit_web
    depends_on:
     - db
    networks:
      - main
    ports:
      - '8000:8000'
    volumes:
      - static_data:/vol/web
    restart: always

  api:
    image: ${DOCKER_USERNAME}/minitwit_api
    container_name: minitwit_api
    depends_on:
     - db
    networks:
      - main
    ports:
      - '9000:9000'
    restart: always

  proxy:
    image: ${DOCKER_USERNAME}/minitwit_proxy
    container_name: minitwit_proxy
    depends_on:
      - web
      - api
    networks:
      - main
    ports:
      - '80:8080'
    volumes:
      - static_data:/vol/static
    restart: always


volumes:
  postgres:
  static_data:
