version: "3.5"

services:
  web:
    image: ${DOCKER_USERNAME}/minitwit_web
    container_name: minitwit_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_data:/vol/web
    deploy:
      replicas: 2
      restart_policy:
        max_attempts: 3
        condition: on-failure

  api:
    image: ${DOCKER_USERNAME}/minitwit_api
    container_name: minitwit_api
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - static_data:/vol/api
    deploy:
      replicas: 2
      restart_policy:
        max_attempts: 3
        condition: on-failure

  proxy:
    image: ${DOCKER_USERNAME}/minitwit_proxy
    container_name: minitwit_proxy
    depends_on:
      - web
      - api
    ports:
      - "80:8080"
    volumes:
      - static_data:/vol/static
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - proxy
    ports:
      - "9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.role == manager

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.2.0"
    restart: always
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres:
  static_data:
  grafana_data:
  prometheus_data:
